### ISSUE TITLE
Could we host content too ?

### ISSUE THREAD

**Issue by pascalandy** [kobmic/ghost-mongodb-storage#1]
Hey Michael,

I understand that your module acts as the picture host server. Is this a usual thing for MongoDB to host pictures?

Why one should care about this module. 1) The main use case IMO, would be to load balance between picture host. Does this make sense? 2) Backup: I can also envision a Master-Master replication setup on different VPS and even different IaaS.

My question for you is: Would it be possible to store the content(i.e. ghost.db) into Mongodb as well ? Right now I'm using Mariadb for this purpose and I would be great to only use Mongodb for the both usage.

Cheers!
Pascal

**Comment by kobmic** [comment]
Hi Pascal,

I really like mongodb, but it wouldn't be the first thing on my mind when storing images. When expecting high load on your ghost blog I would rather recommend storing images on Amazon S3.

Main use case for me writing the mongodb storage module was running a low cost ghost blog on heroku (free dyno & free sandbox mongolab, postgres and mailgun). You cannot store images in the filesystem when running on Heroku (or other PAAS, like Elastic Beanstalk). 

I don't know if it is possible to add a custom storage module for the content in ghost as well, never looked into that. 

Cheers
/Mike

**Comment by pascalandy** [comment]
Thanks for letting me know. Make a lot of sense now! 

Cheers!
Pascal
